name: Benchmarks

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - "benches/**"
      - "frameworks/**"

jobs:
  prepare:
    name: Prepare
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - run: npm ci
      - run: npm run setup all
      - run: npm run build
      - run: npm run publish
      - uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist

  bench_01_run1k:
    name: Bench 01_run1k
    runs-on: ubuntu-latest
    needs: prepare
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - name: Run npm ci
        shell: bash
        run: |
          [[ "$(uname -o)" == "Msys" ]] && exe="chromedriver.exe" || exe="chromedriver"
          export CHROMEDRIVER_FILEPATH=$(which $exe)
          echo $CHROMEDRIVER_FILEPATH
          npm ci
      - uses: actions/download-artifact@v2
        with:
          name: dist
      - run: node ./scripts bench -b 01_run1k
      - uses: actions/upload-artifact@v2
        with:
          name: results
          path: results/01_run1k.json

  bench_02_replace1k:
    name: Bench 02_replace1k
    runs-on: ubuntu-latest
    needs: prepare
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - name: Run npm ci
        shell: bash
        run: |
          [[ "$(uname -o)" == "Msys" ]] && exe="chromedriver.exe" || exe="chromedriver"
          export CHROMEDRIVER_FILEPATH=$(which $exe)
          echo $CHROMEDRIVER_FILEPATH
          npm ci
      - uses: actions/download-artifact@v2
        with:
          name: dist
      - run: node ./scripts bench -b 02_replace1k
      - uses: actions/upload-artifact@v2
        with:
          name: results
          path: results/02_replace1k.json

  bench_03_update10th1k:
    name: Bench 03_update10th1k
    runs-on: ubuntu-latest
    needs: prepare
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - name: Run npm ci
        shell: bash
        run: |
          [[ "$(uname -o)" == "Msys" ]] && exe="chromedriver.exe" || exe="chromedriver"
          export CHROMEDRIVER_FILEPATH=$(which $exe)
          echo $CHROMEDRIVER_FILEPATH
          npm ci
      - uses: actions/download-artifact@v2
        with:
          name: dist
      - run: node ./scripts bench -b 03_update10th1k
      - uses: actions/upload-artifact@v2
        with:
          name: results
          path: results/03_update10th1k_x16.json

  bench_04_select1k:
    name: Bench 04_select1k
    runs-on: ubuntu-latest
    needs: prepare
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - name: Run npm ci
        shell: bash
        run: |
          [[ "$(uname -o)" == "Msys" ]] && exe="chromedriver.exe" || exe="chromedriver"
          export CHROMEDRIVER_FILEPATH=$(which $exe)
          echo $CHROMEDRIVER_FILEPATH
          npm ci
      - uses: actions/download-artifact@v2
        with:
          name: dist
      - run: node ./scripts bench -b 04_select1k
      - uses: actions/upload-artifact@v2
        with:
          name: results
          path: results/04_select1k.json

  bench_05_swap1k:
    name: Bench 05_swap1k
    runs-on: ubuntu-latest
    needs: prepare
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - name: Run npm ci
        shell: bash
        run: |
          [[ "$(uname -o)" == "Msys" ]] && exe="chromedriver.exe" || exe="chromedriver"
          export CHROMEDRIVER_FILEPATH=$(which $exe)
          echo $CHROMEDRIVER_FILEPATH
          npm ci
      - uses: actions/download-artifact@v2
        with:
          name: dist
      - run: node ./scripts bench -b 05_swap1k
      - uses: actions/upload-artifact@v2
        with:
          name: results
          path: results/05_swap1k.json

  bench_06_remove-one-1k:
    name: Bench 06_remove-one-1k
    runs-on: ubuntu-latest
    needs: prepare
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - name: Run npm ci
        shell: bash
        run: |
          [[ "$(uname -o)" == "Msys" ]] && exe="chromedriver.exe" || exe="chromedriver"
          export CHROMEDRIVER_FILEPATH=$(which $exe)
          echo $CHROMEDRIVER_FILEPATH
          npm ci
      - uses: actions/download-artifact@v2
        with:
          name: dist
      - run: node ./scripts bench -b 06_remove-one-1k
      - uses: actions/upload-artifact@v2
        with:
          name: results
          path: results/06_remove-one-1k.json

  bench_07_create10k:
    name: Bench 07_create10k
    runs-on: ubuntu-latest
    needs: prepare
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - name: Run npm ci
        shell: bash
        run: |
          [[ "$(uname -o)" == "Msys" ]] && exe="chromedriver.exe" || exe="chromedriver"
          export CHROMEDRIVER_FILEPATH=$(which $exe)
          echo $CHROMEDRIVER_FILEPATH
          npm ci
      - uses: actions/download-artifact@v2
        with:
          name: dist
      - run: node ./scripts bench -b 07_create10k
      - uses: actions/upload-artifact@v2
        with:
          name: results
          path: results/07_create10k.json

  bench_08_create1k-after1k:
    name: Bench 08_create1k-after1k
    runs-on: ubuntu-latest
    needs: prepare
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - name: Run npm ci
        shell: bash
        run: |
          [[ "$(uname -o)" == "Msys" ]] && exe="chromedriver.exe" || exe="chromedriver"
          export CHROMEDRIVER_FILEPATH=$(which $exe)
          echo $CHROMEDRIVER_FILEPATH
          npm ci
      - uses: actions/download-artifact@v2
        with:
          name: dist
      - run: node ./scripts bench -b 08_create1k-after1k
      - uses: actions/upload-artifact@v2
        with:
          name: results
          path: results/08_create1k-after1k_x2.json

  bench_09_clear1k:
    name: Bench 09_clear1k
    runs-on: ubuntu-latest
    needs: prepare
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - name: Run npm ci
        shell: bash
        run: |
          [[ "$(uname -o)" == "Msys" ]] && exe="chromedriver.exe" || exe="chromedriver"
          export CHROMEDRIVER_FILEPATH=$(which $exe)
          echo $CHROMEDRIVER_FILEPATH
          npm ci
      - uses: actions/download-artifact@v2
        with:
          name: dist
      - run: node ./scripts bench -b 09_clear1k
      - uses: actions/upload-artifact@v2
        with:
          name: results
          path: results/09_clear1k_x8.json
