name: CI-master

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Cache node modules
        uses: actions/cache@v1
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - run: npm ci
      - run: npm run setup all
      - run: npm run build
      - run: npm run publish
      - uses: actions/upload-artifact@v1
        with:
          name: dist
          path: dist

  publish:
    name: Publish
    needs: build
    runs-on: ubuntu-latest
    env:
      PUBLISH_BRANCH: gh-pages
      CHANGES: ""
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - uses: actions/checkout@v2
        with:
          ref: ${{ env.PUBLISH_BRANCH }}
      - name: Configure local repo
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "${{ github.workflow }} Github Action"
      - uses: actions/download-artifact@v1
        with:
          name: dist
          path: .
      - name: Determine changes
        run: |
          git status -s
          export CHANGES=$(git status -s)
      - name: Commit changes
        if: env.CHANGES != ''
        run: |
          git add .
          git commit -m "Updates from ${{ github.workflow }}#${{ github.run_number }}"
      - name: Push changes
        if: env.CHANGES != ''
        run: git push origin ${{ env.PUBLISH_BRANCH }}
